MILVUS:
    url: "http://124.220.221.33:19530"

ELASTICSEARCH:
    url: "http://124.220.221.33:9200"
    index: "patent_law"

MYSQL:
    host: "124.220.221.33"
    port: 3306
    user: "root"
    password: "fayiyoudao"
    database: "lawtalk"


  