MILVUS:
    url: "http://localhost:19530"

ELASTICSEARCH:
    url: "http://localhost:9200"
    index: "patent_law"

MYSQL:
    host: "localhost"
    port: 3306
    user: "root"
    password: "fayiyoudao"
    database: "lawtalk"


  
