MILVUS:
    url: "输入你的milvus url"

ELASTICSEARCH:
    url: "输入你的ELASTICSEARCH url"
    index: "输入你的index"

MYSQL:
    host: "输入你的mysql host"
    port: 3306
    user: "root"
    password: "输入密码"
    database: "输入数据库名"


  
