#zhipuAI调用
zhipuAI:
    api_key: "输入你的api_key"

#openai调用
aliAI:
    api_key: "输入你的api_key"
    base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"

#openai调用
deepseekAI:
    api_key: "输入你的api_key"
    base_url: "https://api.deepseek.com/v1"

#Ark调用 from volcenginesdkarkruntime import Ark

doubaoAI:
    api_key: "输入你的api_key"
    ep_point: "输入你的api节点"
    base_url: "https://ark.cn-beijing.volces.com/api/v3"

baichuanAI:
    api_key: "输入你的api_key"
    base_url:  "https://api.baichuan-ai.com/v1/"


doubaoembedding:
    api_key: "输入你的api_key"
    ep_point: "输入你的节点"
    base_url: "https://ark.cn-beijing.volces.com/api/v3"
       

